services:
  web:
    build: .
    env_file: .env
    depends_on:
      - db
    ports:
     - "${WEB_PORT:-8000}:8000"
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn cinema_base.wsgi:application --bind 0.0.0.0:8000"
    environment:
      DJANGO_SETTINGS_MODULE: cinema_base.settings.prod
      POSTGRES_HOST: db
  db:
    image: postgres:16
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: