"""
Django settings for cinema_base project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
from dotenv import load_dotenv
import os

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "movie",
    "user",
    "rest_framework",
    "drf_spectacular",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "cinema_base.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "cinema_base.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    "default": {
        "BACKEND": "django.core.mail.backends.console.EmailBackend",
    },
}


AUTH_USER_MODEL = "user.User"


REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 14,
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
}

SPECTACULAR_SETTINGS = {
    "TITLE": "CineBase API",
    "DESCRIPTION": (
        "Backend for the **CineBase** movie catalog: browse and search "
        "movies, rate them, keep a watchlist and discuss them in comments.\n\n"
        "**Authentication.** Register via `POST /api/user/register/`, "
        "then log in via `POST /api/user/token/` with your email and "
        "password. Copy the `access` token from the response, click the "
        "**Authorize** button at the top of this page and paste the token "
        "there. Now all requests are sent as you. "
        "The access token lives 60 minutes: when it expires, get a new one "
        "via `POST /api/user/token/refresh/` (the refresh token lives "
        "7 days) and paste it into **Authorize** again.\n\n"
        "**Pagination.** Lists return `count`, `next`, `previous` and "
        "`results`; use `?page=N`.\n\n"
        "**Images.** `poster_path`, `backdrop_path` and `profile_path` are "
        "partial paths. Full URL = `base_url` + `size` + `path`, "
        "see `GET /api/config/images/`.\n\n"
        '**Errors.** `400` validation: `{"field": ["message"]}`. '
        "`401` token missing or expired, `403` no permission, `404` not "
        'found: all three come as `{"detail": "message"}`.'
    ),
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "SCHEMA_PATH_PREFIX": "/api",
    "TAGS": [
        {
            "name": "user",
            "description": "Registration, login and profile.\n\n"
            "- **No token needed:** `register`, `token`, `token/refresh`, "
            "`token/verify`\n"
            "- **Needs a token:** `me`",
        },
        {
            "name": "movies",
            "description": "Catalog, search, filters and movie details.\n\n"
            "- **No token needed:** list, search, filter, details\n"
            "- **Needs a token:** my rating, my watchlist\n"
            "- **Admin only:** create, edit, delete movies",
        },
        {
            "name": "comments",
            "description": "Comments, replies and likes.\n\n"
            "- **No token needed:** read comments\n"
            "- **Needs a token:** add a comment, like\n"
            "- **Author or admin:** delete a comment",
        },
        {
            "name": "genres",
            "description": "List of genres for the movie filter. "
            "**No token needed.**",
        },
        {
            "name": "config",
            "description": "Base URL and sizes for building image links. "
            "**No token needed.**",
        },
    ],
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
}
