# Generated by Django 6.1.1 on 2026-10-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0003_alter_comment_movie_alter_comment_parent_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="movie",
            options={"ordering": ["-popularity"]},
        ),
        migrations.RemoveField(
            model_name="movie",
            name="original_language",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="status",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="tagline",
        ),
        migrations.AddField(
            model_name="movie",
            name="release_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="vote_average",
            field=models.FloatField(db_index=True, default=0),
        ),
    ]
