# Generated by Django 6.1.1 on 2026-10-03 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0004_alter_movie_options_remove_movie_original_language_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-created_at"]},
        ),
    ]
