# Generated by Django 6.1.1 on 2026-10-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0005_alter_comment_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="trailer_youtube_id",
            field=models.TextField(blank=True, null=True),
        ),
    ]
