# Generated by Django 6.1.1 on 2026-10-05 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0006_movie_trailer_youtube_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moviecast",
            name="character",
            field=models.TextField(),
        ),
    ]
